name: car_dealer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.2
  google_fonts: ^2.0.0
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.2
  button3d: ^0.1.1
  cupertino_icons: ^0.1.3
  collapsible_sidebar: ^1.0.7+2
  provider: ^5.0.0
  material_design_icons_flutter: ^4.0.5855
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.7.3
  firebase_storage: ^8.0.0
  permission_handler: ^6.1.1
  path: ^1.7.0
  form_field_validator: ^1.0.1
  toast: ^0.1.5
  http: ^0.13.0
  multi_image_picker: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Sansita
      fonts:
        - asset: assets/fonts/SansitaSwashed-SemiBold.ttf
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Alegreya-Black.ttf
